# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telas_Seguranca.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 825)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.menu_icons = QtWidgets.QWidget(self.centralwidget)
        self.menu_icons.setMinimumSize(QtCore.QSize(100, 0))
        self.menu_icons.setStyleSheet("QWidget{\n"
"    background-color:#069E6E;\n"
"}")
        self.menu_icons.setObjectName("menu_icons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_icons)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnHomeLateral = QtWidgets.QPushButton(self.menu_icons)
        self.btnHomeLateral.setMinimumSize(QtCore.QSize(0, 80))
        self.btnHomeLateral.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}")
        self.btnHomeLateral.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagens/imgBtnHome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHomeLateral.setIcon(icon)
        self.btnHomeLateral.setIconSize(QtCore.QSize(36, 36))
        self.btnHomeLateral.setCheckable(True)
        self.btnHomeLateral.setAutoExclusive(True)
        self.btnHomeLateral.setObjectName("btnHomeLateral")
        self.verticalLayout.addWidget(self.btnHomeLateral)
        self.btnScannerLateral = QtWidgets.QPushButton(self.menu_icons)
        self.btnScannerLateral.setMinimumSize(QtCore.QSize(0, 80))
        self.btnScannerLateral.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}")
        self.btnScannerLateral.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imagens/imgBtnRFacial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScannerLateral.setIcon(icon1)
        self.btnScannerLateral.setIconSize(QtCore.QSize(36, 36))
        self.btnScannerLateral.setCheckable(True)
        self.btnScannerLateral.setAutoExclusive(True)
        self.btnScannerLateral.setObjectName("btnScannerLateral")
        self.verticalLayout.addWidget(self.btnScannerLateral)
        self.btnEntradasLateral = QtWidgets.QPushButton(self.menu_icons)
        self.btnEntradasLateral.setMinimumSize(QtCore.QSize(0, 80))
        self.btnEntradasLateral.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}")
        self.btnEntradasLateral.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imagens/imgBtnEntrada.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEntradasLateral.setIcon(icon2)
        self.btnEntradasLateral.setIconSize(QtCore.QSize(36, 36))
        self.btnEntradasLateral.setCheckable(True)
        self.btnEntradasLateral.setAutoExclusive(True)
        self.btnEntradasLateral.setObjectName("btnEntradasLateral")
        self.verticalLayout.addWidget(self.btnEntradasLateral)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 465, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnVoltarLateral = QtWidgets.QPushButton(self.menu_icons)
        self.btnVoltarLateral.setMinimumSize(QtCore.QSize(0, 80))
        self.btnVoltarLateral.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnVoltarLateral.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imagens/imgBtnVoltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoltarLateral.setIcon(icon3)
        self.btnVoltarLateral.setIconSize(QtCore.QSize(36, 36))
        self.btnVoltarLateral.setObjectName("btnVoltarLateral")
        self.verticalLayout_3.addWidget(self.btnVoltarLateral)
        self.btnDesconectarLateral = QtWidgets.QPushButton(self.menu_icons)
        self.btnDesconectarLateral.setMinimumSize(QtCore.QSize(0, 80))
        self.btnDesconectarLateral.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnDesconectarLateral.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imagens/imgBtnDesconectar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDesconectarLateral.setIcon(icon4)
        self.btnDesconectarLateral.setIconSize(QtCore.QSize(34, 34))
        self.btnDesconectarLateral.setObjectName("btnDesconectarLateral")
        self.verticalLayout_3.addWidget(self.btnDesconectarLateral)
        self.gridLayout.addWidget(self.menu_icons, 1, 0, 1, 1)
        self.menu_todo = QtWidgets.QWidget(self.centralwidget)
        self.menu_todo.setMinimumSize(QtCore.QSize(200, 50))
        self.menu_todo.setStyleSheet("QWidget{\n"
"    background-color:#069E6E;\n"
"}")
        self.menu_todo.setObjectName("menu_todo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_todo)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnHomeLAberto = QtWidgets.QPushButton(self.menu_todo)
        self.btnHomeLAberto.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnHomeLAberto.setFont(font)
        self.btnHomeLAberto.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}")
        self.btnHomeLAberto.setIcon(icon)
        self.btnHomeLAberto.setIconSize(QtCore.QSize(36, 36))
        self.btnHomeLAberto.setCheckable(True)
        self.btnHomeLAberto.setAutoExclusive(True)
        self.btnHomeLAberto.setObjectName("btnHomeLAberto")
        self.verticalLayout_2.addWidget(self.btnHomeLAberto)
        self.btnScannerLAberto = QtWidgets.QPushButton(self.menu_todo)
        self.btnScannerLAberto.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnScannerLAberto.setFont(font)
        self.btnScannerLAberto.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"")
        self.btnScannerLAberto.setIcon(icon1)
        self.btnScannerLAberto.setIconSize(QtCore.QSize(36, 36))
        self.btnScannerLAberto.setCheckable(True)
        self.btnScannerLAberto.setAutoExclusive(True)
        self.btnScannerLAberto.setObjectName("btnScannerLAberto")
        self.verticalLayout_2.addWidget(self.btnScannerLAberto)
        self.btnEntradasLAberto = QtWidgets.QPushButton(self.menu_todo)
        self.btnEntradasLAberto.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnEntradasLAberto.setFont(font)
        self.btnEntradasLAberto.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"\n"
"")
        self.btnEntradasLAberto.setIcon(icon2)
        self.btnEntradasLAberto.setIconSize(QtCore.QSize(36, 36))
        self.btnEntradasLAberto.setCheckable(True)
        self.btnEntradasLAberto.setAutoExclusive(True)
        self.btnEntradasLAberto.setObjectName("btnEntradasLAberto")
        self.verticalLayout_2.addWidget(self.btnEntradasLAberto)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 465, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btnVoltarLAberto = QtWidgets.QPushButton(self.menu_todo)
        self.btnVoltarLAberto.setMinimumSize(QtCore.QSize(0, 80))
        self.btnVoltarLAberto.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnVoltarLAberto.setIcon(icon3)
        self.btnVoltarLAberto.setIconSize(QtCore.QSize(36, 36))
        self.btnVoltarLAberto.setObjectName("btnVoltarLAberto")
        self.verticalLayout_4.addWidget(self.btnVoltarLAberto)
        self.btnDesconectarLAberto = QtWidgets.QPushButton(self.menu_todo)
        self.btnDesconectarLAberto.setMinimumSize(QtCore.QSize(0, 80))
        self.btnDesconectarLAberto.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnDesconectarLAberto.setIcon(icon4)
        self.btnDesconectarLAberto.setIconSize(QtCore.QSize(32, 32))
        self.btnDesconectarLAberto.setObjectName("btnDesconectarLAberto")
        self.verticalLayout_4.addWidget(self.btnDesconectarLAberto)
        self.gridLayout.addWidget(self.menu_todo, 1, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0.125 rgba(0, 135, 92, 255), stop:0.875 rgba(0, 66, 50, 198));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_Home = QtWidgets.QWidget()
        self.pg_Home.setObjectName("pg_Home")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pg_Home)
        self.gridLayout_6.setContentsMargins(50, 150, 50, 150)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.pg_Home)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.frame_4)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 90))
        self.label_2.setMaximumSize(QtCore.QSize(700, 90))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(66)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_7.addWidget(self.widget_4, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 3, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnDesconectar_PgHome = QtWidgets.QPushButton(self.frame_5)
        self.btnDesconectar_PgHome.setMinimumSize(QtCore.QSize(300, 50))
        self.btnDesconectar_PgHome.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnDesconectar_PgHome.setFont(font)
        self.btnDesconectar_PgHome.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnDesconectar_PgHome.setIcon(icon4)
        self.btnDesconectar_PgHome.setIconSize(QtCore.QSize(36, 36))
        self.btnDesconectar_PgHome.setObjectName("btnDesconectar_PgHome")
        self.gridLayout_9.addWidget(self.btnDesconectar_PgHome, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_Home)
        self.pg_Entradas = QtWidgets.QWidget()
        self.pg_Entradas.setObjectName("pg_Entradas")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pg_Entradas)
        self.gridLayout_3.setContentsMargins(50, 50, 50, 50)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.pg_Entradas)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.etyPesquisar_PgEntradas = QtWidgets.QLineEdit(self.frame_2)
        self.etyPesquisar_PgEntradas.setMinimumSize(QtCore.QSize(450, 0))
        self.etyPesquisar_PgEntradas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.etyPesquisar_PgEntradas.setStyleSheet("QLineEdit{\n"
"    background-color:#069E6E;\n"
"    border: 2px solid #069E6E;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"")
        self.etyPesquisar_PgEntradas.setObjectName("etyPesquisar_PgEntradas")
        self.horizontalLayout_2.addWidget(self.etyPesquisar_PgEntradas)
        self.btnPesquisar_PgEntradas = QtWidgets.QPushButton(self.frame_2)
        self.btnPesquisar_PgEntradas.setMinimumSize(QtCore.QSize(60, 30))
        self.btnPesquisar_PgEntradas.setMaximumSize(QtCore.QSize(606, 30))
        self.btnPesquisar_PgEntradas.setStyleSheet("QPushButton{\n"
"    background-color:#047b55;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(44, 97, 70);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"")
        self.btnPesquisar_PgEntradas.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imagens/imgPesquisar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar_PgEntradas.setIcon(icon5)
        self.btnPesquisar_PgEntradas.setIconSize(QtCore.QSize(25, 25))
        self.btnPesquisar_PgEntradas.setObjectName("btnPesquisar_PgEntradas")
        self.horizontalLayout_2.addWidget(self.btnPesquisar_PgEntradas)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.tbl_historicoEntradas = QtWidgets.QTableWidget(self.frame_2)
        self.tbl_historicoEntradas.setMinimumSize(QtCore.QSize(0, 500))
        self.tbl_historicoEntradas.setMaximumSize(QtCore.QSize(16777215, 650))
        self.tbl_historicoEntradas.setRowCount(20)
        self.tbl_historicoEntradas.setObjectName("tbl_historicoEntradas")
        self.tbl_historicoEntradas.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_historicoEntradas.setHorizontalHeaderItem(5, item)
        self.tbl_historicoEntradas.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_5.addWidget(self.tbl_historicoEntradas)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_Entradas)
        self.pg_Scanner = QtWidgets.QWidget()
        self.pg_Scanner.setObjectName("pg_Scanner")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pg_Scanner)
        self.gridLayout_4.setContentsMargins(50, 50, 50, 50)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.pg_Scanner)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(80, -1, 80, 26)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_tituloScanner = QtWidgets.QLabel(self.frame_9)
        self.lbl_tituloScanner.setMinimumSize(QtCore.QSize(0, 60))
        self.lbl_tituloScanner.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.lbl_tituloScanner.setFont(font)
        self.lbl_tituloScanner.setObjectName("lbl_tituloScanner")
        self.horizontalLayout_14.addWidget(self.lbl_tituloScanner)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setStyleSheet("QFrame{\n"
"    border: 10px solid #069E6E;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_dataDoDia = QtWidgets.QLabel(self.frame)
        self.lbl_dataDoDia.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_dataDoDia.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_dataDoDia.setFont(font)
        self.lbl_dataDoDia.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_dataDoDia.setObjectName("lbl_dataDoDia")
        self.horizontalLayout_6.addWidget(self.lbl_dataDoDia)
        spacerItem14 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.lbl_horarioDoDia = QtWidgets.QLabel(self.frame)
        self.lbl_horarioDoDia.setMinimumSize(QtCore.QSize(0, 24))
        self.lbl_horarioDoDia.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_horarioDoDia.setFont(font)
        self.lbl_horarioDoDia.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_horarioDoDia.setObjectName("lbl_horarioDoDia")
        self.horizontalLayout_6.addWidget(self.lbl_horarioDoDia)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbl_imgValidacao = QtWidgets.QLabel(self.frame_6)
        self.lbl_imgValidacao.setMinimumSize(QtCore.QSize(130, 130))
        self.lbl_imgValidacao.setMaximumSize(QtCore.QSize(130, 130))
        self.lbl_imgValidacao.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_imgValidacao.setObjectName("lbl_imgValidacao")
        self.horizontalLayout_11.addWidget(self.lbl_imgValidacao)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.lbl_nome = QtWidgets.QLabel(self.frame_7)
        self.lbl_nome.setMinimumSize(QtCore.QSize(60, 20))
        self.lbl_nome.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_nome.setFont(font)
        self.lbl_nome.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_nome.setObjectName("lbl_nome")
        self.horizontalLayout_7.addWidget(self.lbl_nome)
        self.lbl_nomeAluno = QtWidgets.QLabel(self.frame_7)
        self.lbl_nomeAluno.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_nomeAluno.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_nomeAluno.setFont(font)
        self.lbl_nomeAluno.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_nomeAluno.setObjectName("lbl_nomeAluno")
        self.horizontalLayout_7.addWidget(self.lbl_nomeAluno)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        self.lbl_RM = QtWidgets.QLabel(self.frame_7)
        self.lbl_RM.setMinimumSize(QtCore.QSize(40, 20))
        self.lbl_RM.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_RM.setFont(font)
        self.lbl_RM.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_RM.setObjectName("lbl_RM")
        self.horizontalLayout_8.addWidget(self.lbl_RM)
        self.lbl_RmAluno = QtWidgets.QLabel(self.frame_7)
        self.lbl_RmAluno.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_RmAluno.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_RmAluno.setFont(font)
        self.lbl_RmAluno.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_RmAluno.setObjectName("lbl_RmAluno")
        self.horizontalLayout_8.addWidget(self.lbl_RmAluno)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.lbl_periodo = QtWidgets.QLabel(self.frame_7)
        self.lbl_periodo.setMinimumSize(QtCore.QSize(80, 20))
        self.lbl_periodo.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_periodo.setFont(font)
        self.lbl_periodo.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_periodo.setObjectName("lbl_periodo")
        self.horizontalLayout_9.addWidget(self.lbl_periodo)
        self.lbl_periodoAluno = QtWidgets.QLabel(self.frame_7)
        self.lbl_periodoAluno.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_periodoAluno.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_periodoAluno.setFont(font)
        self.lbl_periodoAluno.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_periodoAluno.setObjectName("lbl_periodoAluno")
        self.horizontalLayout_9.addWidget(self.lbl_periodoAluno)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbl_imgStatusHorario = QtWidgets.QLabel(self.frame_8)
        self.lbl_imgStatusHorario.setMinimumSize(QtCore.QSize(70, 70))
        self.lbl_imgStatusHorario.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lbl_imgStatusHorario.setFont(font)
        self.lbl_imgStatusHorario.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_imgStatusHorario.setObjectName("lbl_imgStatusHorario")
        self.horizontalLayout_10.addWidget(self.lbl_imgStatusHorario)
        self.lbl_infosAcesso = QtWidgets.QLabel(self.frame_8)
        self.lbl_infosAcesso.setMinimumSize(QtCore.QSize(210, 22))
        self.lbl_infosAcesso.setMaximumSize(QtCore.QSize(210, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_infosAcesso.setFont(font)
        self.lbl_infosAcesso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_infosAcesso.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}")
        self.lbl_infosAcesso.setObjectName("lbl_infosAcesso")
        self.horizontalLayout_10.addWidget(self.lbl_infosAcesso)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_6.addWidget(self.frame)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_Scanner)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 1, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setStyleSheet("QWidget{\n"
" background-color:#ffffff;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnIconMenu = QtWidgets.QPushButton(self.widget)
        self.btnIconMenu.setMinimumSize(QtCore.QSize(100, 80))
        self.btnIconMenu.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:#069E6E;\n"
"}\n"
"\n"
"")
        self.btnIconMenu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/imagens/imgBtnMenu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIconMenu.setIcon(icon6)
        self.btnIconMenu.setIconSize(QtCore.QSize(30, 32))
        self.btnIconMenu.setCheckable(True)
        self.btnIconMenu.setObjectName("btnIconMenu")
        self.horizontalLayout_3.addWidget(self.btnIconMenu)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem23)
        self.btnScanner = QtWidgets.QPushButton(self.widget)
        self.btnScanner.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnScanner.setFont(font)
        self.btnScanner.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnScanner.setIcon(icon1)
        self.btnScanner.setIconSize(QtCore.QSize(36, 36))
        self.btnScanner.setObjectName("btnScanner")
        self.horizontalLayout_3.addWidget(self.btnScanner)
        spacerItem24 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem24)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(60, 70))
        self.label_4.setMaximumSize(QtCore.QSize(60, 70))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/imagens/imgLogo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem25 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.btnEntradas = QtWidgets.QPushButton(self.widget)
        self.btnEntradas.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEntradas.setFont(font)
        self.btnEntradas.setStyleSheet("QPushButton{\n"
"    background-color:#069E6E;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#047b55;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(2, 45, 29);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:  rgb(2, 45, 29);\n"
"}\n"
"\n"
"")
        self.btnEntradas.setIcon(icon2)
        self.btnEntradas.setIconSize(QtCore.QSize(36, 36))
        self.btnEntradas.setObjectName("btnEntradas")
        self.horizontalLayout_3.addWidget(self.btnEntradas)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.btnIconMenu.toggled['bool'].connect(self.menu_icons.setVisible) # type: ignore
        self.btnIconMenu.toggled['bool'].connect(self.menu_todo.setHidden) # type: ignore
        self.btnHomeLateral.toggled['bool'].connect(self.btnHomeLAberto.setChecked) # type: ignore
        self.btnScannerLateral.toggled['bool'].connect(self.btnScannerLAberto.setChecked) # type: ignore
        self.btnEntradasLateral.toggled['bool'].connect(self.btnEntradasLAberto.setChecked) # type: ignore
        self.btnHomeLAberto.toggled['bool'].connect(self.btnHomeLateral.setChecked) # type: ignore
        self.btnScannerLAberto.toggled['bool'].connect(self.btnScannerLateral.setChecked) # type: ignore
        self.btnEntradasLAberto.toggled['bool'].connect(self.btnEntradasLateral.setChecked) # type: ignore
        self.btnDesconectarLAberto.clicked.connect(MainWindow.close) # type: ignore
        self.btnDesconectarLateral.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Segurança | Sistema de Reconhecimento Facial"))
        self.btnHomeLAberto.setText(_translate("MainWindow", "Início"))
        self.btnScannerLAberto.setText(_translate("MainWindow", "Scanner"))
        self.btnEntradasLAberto.setText(_translate("MainWindow", "Entradas"))
        self.btnVoltarLAberto.setText(_translate("MainWindow", " Voltar"))
        self.btnDesconectarLAberto.setText(_translate("MainWindow", " Desconectar"))
        self.label_2.setText(_translate("MainWindow", "Olá, Nome"))
        self.btnDesconectar_PgHome.setText(_translate("MainWindow", " Desconectar"))
        self.label_3.setText(_translate("MainWindow", "HISTÓRICO DE ENTRADAS"))
        self.etyPesquisar_PgEntradas.setPlaceholderText(_translate("MainWindow", "Filtre as entradas específicas usando os paramêtros da tabela."))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RM"))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Período"))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Horário"))
        item = self.tbl_historicoEntradas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.lbl_tituloScanner.setText(_translate("MainWindow", "SCANNER"))
        self.lbl_dataDoDia.setText(_translate("MainWindow", "data"))
        self.lbl_horarioDoDia.setText(_translate("MainWindow", "horario"))
        self.lbl_imgValidacao.setText(_translate("MainWindow", "imagem"))
        self.lbl_nome.setText(_translate("MainWindow", "Nome:"))
        self.lbl_nomeAluno.setText(_translate("MainWindow", "???"))
        self.lbl_RM.setText(_translate("MainWindow", "RM:"))
        self.lbl_RmAluno.setText(_translate("MainWindow", "???"))
        self.lbl_periodo.setText(_translate("MainWindow", "Período:"))
        self.lbl_periodoAluno.setText(_translate("MainWindow", "???"))
        self.lbl_imgStatusHorario.setText(_translate("MainWindow", "ima"))
        self.lbl_infosAcesso.setText(_translate("MainWindow", "Acesso Liberado:"))
        self.btnScanner.setText(_translate("MainWindow", "Scanner"))
        self.btnEntradas.setText(_translate("MainWindow", "Entradas"))
import imagens.imagens_usadas_rc
